
/*!
** @file   ObjDict.h
** @author CAN Festival -- NNP
** @date   OD File produced: 2011-05-21 12:20:34.445000
**
** @brief This file is generated by the NNP Tool -- Object Dictionary Editor, as 
** originally developed by CAN Festival and modified by the NNP Team. 
** Specific contents are detailed in Object Dictionary Template.
** Editor modification: 4/29/2010 -- rev 1.0.0 
**
** This ObjDict.h file is generated from NNPPowerModule.odnn
** 
*/  

/*This object dictionary file should only be modified by the Object Dictionary Editor */

#ifndef OBJDICT_H
#define OBJDICT_H

#include "data.h"


#define SCRIPT_DEFAULT_TIME                     80

/* Prototypes of function provided by object dictionnary */
UNS32 ObjDict_valueRangeTest (UNS8 typeValue, void * value);
const indextable * ObjDict_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern UNS32 ObjDict_obj1018_Serial_Number;
extern const UNS32 ObjDict_obj1018_Revision_Number;
extern CO_Data ObjDict_Data;
extern UNS32 Script_Control1;
extern UNS32 Script_Control2;
extern UNS32 Script_Control3;
extern UNS32 Script_Control4;
extern UNS32 Script_Control5;
extern UNS32 Script_Control6;
extern UNS32 Script_Control7;
extern UNS32 Script_Control8;
extern UNS32 Script_Control9;
extern UNS32 Script_Control10;
extern UNS8  ScriptDebug_controlByte;
extern UNS8 ScriptDebug_statusByte; 
extern UNS8 ScriptDebug_currentOpcode;
extern UNS32 ScriptDebug_currentOpAddress;
extern UNS8 ScriptDebug_CurrentExecutionNumber;
extern UNS32 ScriptDebug_currentOpVar0;
extern UNS32 ScriptDebug_currentOpVar1;
extern UNS32 ScriptDebug_currentOpVar2;
extern UNS32 ScriptDebug_currentOpVar3;
extern UNS32 ScriptDebug_currentOpVar4;
extern UNS32 ScriptDebug_currentResultVar;
extern UNS32 ScriptDebug_timerResult;
extern UNS8 ScriptDebug_stackVars[32];
extern UNS8 ScriptDebug_globalVars[32];
extern UNS8 ScriptDebug_varTableSize_SG[10];
extern UNS8 ScriptDebug_JumpValue;
extern UNS8 ScriptDebug_Indication;
extern UNS16 ScriptDebug_stackIndex;
extern UNS16 ScriptDebug_globalIndex;
extern UNS16 ScriptDebug_CRC;
extern UNS8 clockRate;		/* Mapped at index 0x2000, subindex 0x00*/
extern UNS32 Control_SystemControl;		/* Mapped at index 0x2001, subindex 0x01 */
extern UNS8  Control_CurrentGroup;         /* Mapped at index 0x2001, subindex 0x02 */
extern UNS8 Control_StartUp_ScriptPointer;
extern UNS8 Control_ShutDown_ScriptPointer;
extern UNS32 Control_ScriptDelayTime;
extern UNS16 X_Network_X_Network1;		/* Mapped at index 0x2002, subindex 0x01 */
extern UNS16 X_Network_X_Network2;		/* Mapped at index 0x2002, subindex 0x02 */
extern UNS16 Temperature;		/* Mapped at index 0x2003, subindex 0x00*/
extern UNS32 Temperature_Secure;
extern UNS32 DateTime_Date;		/* Mapped at index 0x2004, subindex 0x01 */
extern UNS32 DateTime_Time;		/* Mapped at index 0x2004, subindex 0x02 */
extern UNS32 DateTime_Alarm1;             /* Mapped at index 0x2004, subindex 0x03 */
extern UNS32 DateTime_Alarm2;
extern UNS32 DateTime_Alarm3;
extern UNS32 DateTime_Alarm4;
extern UNS8 DateTime_ClockSet;           /* Mapped at index 0x2004, subindex 0x07 */
extern UNS32 Status_modeSelect;		/* Mapped at index 0x2010, subindex 0x01 */
extern UNS8 Status_numTPDO;
extern UNS8 Status_numTPDO;
extern UNS8 Status_channelSelect;
extern UNS8 Status_profileSelect;
extern UNS8 Status_NodeId;
extern UNS16 Status_TestValue;
extern UNS8 Status_TestValue8;
extern UNS16 Status_TemperatureCount;
extern UNS8 Status_IsOnRadio;
extern UNS8 Status_NumberOfSyncs;
extern UNS16 Status_Auto_PDO_Counter;
extern UNS32 Status_Restore;
extern UNS32 Status_ScriptSkipCounter;
extern UNS32 Status_ScriptsScanTime; 
extern UNS8 Status_StartUp_Script_Status;
extern UNS16 Status_NV_Flash_Status;
extern UNS16 Status_RemoteFlashBlock;
extern UNS32 Status_RemoteFlashBlankCheck;
extern UNS8 AccelerometersPM[4];		/* Mapped at index 0x2011, subindex 0x01*/
extern UNS8 GyrosPM[6];		/* Mapped at index 0x2011, subindex 0x02*/
extern UNS32 AddressRequest;
extern UNS8 memorySelect;
extern UNS8 triggerReadMemory;
extern UNS8 writeByteMemory;
extern UNS8 statusByteMemory;
extern UNS8 ReadMemoryData[36];
extern UNS8 Script_Order[25];
extern UNS16 Script_Management[25];
extern UNS8 TransferBuffer_Working[48];
extern UNS8 TransferBuffer_Copy[48];
extern UNS8 TransferBuffer_Flag;
extern UNS8 TransferBuffer_Counter;
extern UNS8 TransferBuffer_RadioCounter;
extern UNS32 addressCounter;
extern const UNS16 RestoreList[36];
extern UNS8 BatteryControl_PowerControl;		/* Mapped at index 0x3000, subindex 0x01 */
extern UNS8 BatteryControl_BatteryChargingStepIncrement;		/* Mapped at index 0x3000, subindex 0x02 */
extern UNS16 BatteryControl_BatteryChargingInterval;		/* Mapped at index 0x3000, subindex 0x03 */
extern UNS16 BatteryControl_ChargeNFLinkNoChargeLimit;		/* Mapped at index 0x3000, subindex 0x04 */
extern UNS16 BatteryControl_ChargeNFLinkNoChargeStepLimit;		/* Mapped at index 0x3000, subindex 0x05 */
extern UNS8 BatteryControl_BatteryChargeRun;		/* Mapped at index 0x3000, subindex 0x06 */
extern UNS16 BatteryControl_VREC;		/* Mapped at index 0x3000, subindex 0x07 */
extern UNS16 BatteryControl_VSYS;
extern UNS16 BatteryControl_VNET;
extern UNS16 BatteryControl_LOAD;
extern UNS8 BatteryControl_RequestedChargingCurrent;
extern UNS8 BatteryControl_CommandedChargingCurrent;
extern UNS8 ChargingData[21];
extern UNS16 BatteryControl_MinVSYS;
extern UNS8 BatteryControl_LowPowerStatus;
extern UNS8 Battery1Charge_Status[16];		/* Mapped at index 0x3001, subindex 0x01 */
extern UNS8 Battery2Charge_Status[16];		/* Mapped at index 0x3002, subindex 0x01 */
extern UNS8 Battery3Charge_Status[16];		/* Mapped at index 0x3003, subindex 0x01 */
extern UNS8 NetworkPowerControl;
extern UNS8 NetworkVoltage;		/* Mapped at index 0x3010, subindex 0x00*/
extern UNS16 CAN_FormErrors;
extern UNS16 CAN_StuffErrors;
extern UNS16 CAN_BitErrors;
extern UNS16 CAN_OtherErrors;
extern UNS16 CAN_TotalErrors;
extern UNS16 CAN_Receive_BEI;
extern UNS16 CAN_Rx_ErrCounter;
extern UNS16 CAN_Tx_ErrCounter;
extern UNS16 CAN_Receive_Messages;
extern UNS16 CAN_Transmit_Messages;
extern UNS16 CAN_EnabledInterrupts; 
extern UNS16 CAN_RX_ResetCounter;
extern UNS16 CAN_TX_ResetCounter;
extern UNS16 CAN_NS_ResetCounter;
extern UNS8 CAN_ClearOnSYNC;
extern UNS32 CAN_UpTime;
extern UNS8 RADIO_LocalAddress;
extern UNS8 RADIO_RemoteAddress;
extern UNS8 RADIO_ChannelNumber;
extern UNS8 RADIO_RSSI;
extern UNS8 RADIO_LQI;
extern UNS8 RADIO_TXPower;
extern UNS8 RADIO_Sensitivity;
extern UNS16 RADIO_Hard_Bad_CRC;
extern UNS16 RADIO_TX_Sent;
extern UNS16 RADIO_RX_Rec;
extern UNS16 RADIO_RX_Rec_Partial;
extern UNS16 RADIO_SDO_Script_Failures;
extern UNS16 RADIO_WakeInterval;
extern UNS8 RADIO_SessionLength;
extern UNS8 ControlOutput1;
extern UNS8 ControlOutput2;
extern UNS8 ControlOutput3;
extern UNS8 ControlOutput4;
extern UNS8 ControlOutput5;
extern UNS8 ControlOutput6;
extern UNS8 ControlOutput7;
extern UNS8 ControlOutput8;
extern UNS8 StimY[64];
extern UNS8 StatusStimY;

extern char WriteFile_1[];
extern const UNS32 WriteFileSize_1;
extern UNS32 FilePointer;

extern UNS8 StackApp;
extern UNS8 StackCANServer;
extern UNS8 StackCANTimer;
extern UNS8 StackIOScan;
extern UNS8 StackSleep;
extern UNS8 StackScript;
extern UNS8 StackTick;
extern UNS8 StackIdle;
extern UNS8 StackStats;

#endif // OBJDICT_H
